yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path(
        '',
        views.index,
        name='index'
    ),
    path(
        'group/<slug:slug>/',
        views.group_posts,
        name='group'
    ),
    path(
        'profile/<str:username>/',
        views.profile,
        name='profile'
    ),
    path(
        'posts/<int:post_id>/comment',
        views.add_comment,
        name='add_comment'
    ),
    path(
        'posts/<int:post_id>/',
        views.post_detail,
        name='post_detail'
    ),
    path(
        'create/',
        views.post_create,
        name='post_create'
    ),
    path(
        'posts/<post_id>/edit/',
        views.post_edit,
        name='post_edit'
    ),
    path(
        'follow/',
        views.follow_index,
        name='follow_index'
    ),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = 'Админка'
admin.site.index_title = 'Администрирование проекта'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

handler403 = 'core.views.permission_denied'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403csrf = 'core.views.csrf_failure'

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        'Название группы',
        max_length=200,
        help_text='Enter title .......'
    )
    slug = models.SlugField(
        'Представление в url-е',
        unique=True
    )
    description = models.TextField(
        'Описание группы',
        max_length=400
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Группы'
        verbose_name = 'Группу'


class Post(models.Model):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name='groups',
        blank=True,
        null=True,
        verbose_name='Группа',
        help_text='Выберите группу'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    def __str__(self):
        return self.text[:15]

    class Meta:
        verbose_name_plural = 'Публикации'
        verbose_name = 'Публикацию'
        ordering = ('-pub_date',)


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        blank=False,
        null=False,
        verbose_name='Запись'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор комментария'
    )
    text = models.TextField(
        'Текст комментария',
        help_text='Введите текст комментария'
    )
    created = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
    )

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.text


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор'
    )

    class Meta:
        verbose_name = 'Подписку'
        verbose_name_plural = 'Подписки'
        constraints = (
            models.UniqueConstraint(
                fields=('user', 'author',),
                name='follow_unique'
            ),
            models.CheckConstraint(
                name='no_oun_follow',
                check=~models.Q(user=models.F('author'))
            ),
        )

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image',)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.conf import settings
from django.http import HttpResponseRedirect
from django.utils import timezone
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

from .models import Post, Group, Comment, Follow, User
from .forms import PostForm, CommentForm


def paginator_for_all_funcs(request, post_list):
    paginator = Paginator(post_list, settings.POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return page_obj


def index(request):
    template = 'posts/index.html'
    post_list = Post.objects.all()
    context = {
        'page_obj': paginator_for_all_funcs(request, post_list),
    }
    return render(request, template, context)


def group_posts(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    post_list = group.groups.all()
    context = {
        'group': group,
        'page_obj': paginator_for_all_funcs(request, post_list),
    }
    return render(request, template, context)


def profile(request, username):
    template = 'posts/profile.html'
    user = get_object_or_404(User, username=username)
    post_list = (user.posts.select_related('author').
                 select_related('group').all())
    context = {
        'author': user,
        'page_obj': paginator_for_all_funcs(request, post_list),
        'post_list': post_list
    }
    if request.user.is_authenticated:
        authors = Follow.objects.filter(
            user=request.user
        ).values_list('author_id', flat=True)
        if user.id in authors:
            following = True
        else:
            following = False
        context.update({'following': following})
    return render(request, template, context)


def post_detail(request, post_id):
    template = 'posts/post_detail.html'
    post = Post.objects.get(id=post_id)
    authors_posts = Post.objects.filter(author=post.author)
    post_count = authors_posts.count()
    form = CommentForm()
    comments = Comment.objects.filter(post_id=post_id)
    context = {
        'post': post,
        'authors_posts': authors_posts,
        'post_count': post_count,
        'form': form,
        'comments': comments,
    }
    return render(request, template, context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def post_create(request):
    template = 'posts/create_post.html'
    if request.method == 'POST':
        form = PostForm(
            request.POST or None,
            files=request.FILES or None
        )
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.pub_date = timezone.now()
            post.save()
            return redirect('posts:profile', username=request.user.username)
    else:
        form = PostForm()
    context = {
        'form': form,
        'title': 'Новая запись',
        'btn_text': 'Добавить'
    }
    return render(request, template, context)


def post_edit(request, post_id):
    template = 'posts/create_post.html'
    post = get_object_or_404(Post, id=post_id)
    if post.author == request.user:
        if request.method == 'POST':
            form = PostForm(
                request.POST or None,
                files=request.FILES or None,
                instance=post
            )
            if form.is_valid():
                post = form.save(commit=False)
                post.author = request.user
                post.pub_date = timezone.now()
                post.save()
                return redirect('posts:post_detail', post_id=post.id)
        else:
            form = PostForm(instance=post)
        context = {
            'form': form,
            'title': 'Редактировать запись',
            'btn_text': 'Сохранить'
        }
        return render(request, template, context)
    else:
        return redirect('posts:post_detail', post_id=post.id)


@login_required
def follow_index(request):
    template = 'posts/follow.html'
    follower_user = request.user
    user_following_authors = Follow.objects.filter(
        user=follower_user).values('author')
    post_list = Post.objects.filter(author__in=user_following_authors)
    context = {
        'page_obj': paginator_for_all_funcs(request, post_list),
    }
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    # Подписаться на автора
    author = get_object_or_404(User, username=username)
    user = request.user
    if author != user:
        Follow.objects.get_or_create(user=user, author=author)
        return redirect('posts:profile', username=author)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def profile_unfollow(request, username):
    # Дизлайк, отписка
    author = get_object_or_404(User, username=username)
    user = request.user
    Follow.objects.get(user=user, author=author).delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block header %}{{ title }}{% endblock %}
{% block content %}
{% load user_filters%}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {{ title }}
          </div>
          <div class="card-body">
            {% for error in form.errors %}
              <div class="alert alert-danger" role="alert">
                {{ error }}
              </div>
            {% endfor %}
            <form method="post" enctype="multipart/form-data">
              {% csrf_token %}
              <div class="form-group row my-3 p-3">
                <label for="id_text">
                  Текст записи
                  <span class="required text-danger" >*</span>
                </label>
                  {{ form.text|safe }}
                <small id="id_text-help" class="form-text text-muted">
                  Поле для ввода текста записи
                </small>
              </div>
              <div class="form-group row my-3 p-3">
                <label for="id_group">
                  Группа
                </label>
                  {{ form.group|safe }}
                <small id="id_group-help" class="form-text text-muted">
                  Группа, к которой будет относиться запись
                </small>
              </div>
              <div class="form-group row my-3 p-3">
                <label for="id_image">
                  Картинка
                </label>
                  {{ form.image|safe }}
                <small id="id_image-help" class="form-text text-muted">
                  Загружаемая картинка
                </small>
              </div>
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {{ btn_text }}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
{% include 'posts/includes/switcher.html' %}
{% load cache %}
{% load thumbnail %}
<div class="container py-5">
  {% cache 20 follow_page page_obj.number %}
  {% for post in page_obj %}
  <article>
    <ul>
      <li>
        Автор:
        {% if post.author.get_full_name %}
          <a href="{% url 'posts:profile' post.author %}">{{ post.author.get_full_name }}</a>
        {% else %}
          <a href="{% url 'posts:profile' post.author %}">{{ post.author.username }}</a>
        {% endif %}
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text }}</p>
    <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
  </article>
  {% if post.group %}Группа:  <a href="{% url 'posts:group' post.group.slug %}">{{ post.group }}</a>
  {% else %}
  <span>группа не указана</span>
  {% endif %}
  {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% endcache %}
  {% include '../includes/paginator.html' %}
</div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}Записи сообщества {{ group.title }}{% endblock %}
{% block content %}
{% load thumbnail %}
<div class="container py-5">
  <h1>{{ group.title }}</h1>
  <p>{{ group.description }}</p>
  {% for post in page_obj %}
  <article>
    <ul>
      <li>
        Автор:
        {% if post.author.get_full_name %}
        <a href="{% url 'posts:profile' post.author %}">{{ post.author.get_full_name }}</a>
        {% else %}
        <a href="{% url 'posts:profile' post.author %}">{{ post.author.username }}</a>
        {% endif %}
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text }}</p>
    <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
  </article>
  {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include '../includes/paginator.html' %}
</div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
{% include 'posts/includes/switcher.html' %}
{% load cache %}
{% load thumbnail %}
<div class="container py-5">
  {% cache 20 index_page page_obj.number %}
  {% for post in page_obj %}
  <article>
    <ul>
      <li>
        Автор:
        {% if post.author.get_full_name %}
          <a href="{% url 'posts:profile' post.author %}">{{ post.author.get_full_name }}</a>
        {% else %}
          <a href="{% url 'posts:profile' post.author %}">{{ post.author.username }}</a>
        {% endif %}
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text }}</p>
    <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
  </article>
  {% if post.group %}Группа:  <a href="{% url 'posts:group' post.group.slug %}">{{ post.group }}</a>
  {% else %}
  <span>группа не указана</span>
  {% endif %}
  {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% endcache %}
  {% include '../includes/paginator.html' %}
</div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}Запись {{ post.text|truncatechars:30 }}{% endblock %}
{% block content %}
{% load thumbnail %}
<div class="container py-5">
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
        <li class="list-group-item">
          Группа:
          {% if post.group %}<a href="{% url 'posts:group' post.group.slug %}">{{ post.group }} </a>
          {% else %}<span>группа не указана</span>{% endif %}
        </li>
        <li class="list-group-item">
          Автор:
          {% if post.author.get_full_name %}
            <a href="{% url 'posts:profile' post.author %}">{{ post.author.get_full_name }}</a>
          {% else %}
            <a href="{% url 'posts:profile' post.author %}">{{ post.author.username }}</a>
          {% endif %}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
            Всего записей автора:  {{ post_count }}
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>
        {{ post.text }}
      </p>
         <!-- эта кнопка видна только автору -->
      {% if post.author == request.user %}<a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
        редактировать запись
      </a>{% endif %}
    </article>
    {% include "includes/comment.html" %}
  </div>
</div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}Профайл пользователя {{ author }}{% endblock %}
{% block header %}Профайл пользователя {{ author }}{% endblock %}
{% block content %}
{% load thumbnail %}
<div class="container py-5">
  <div class="mb-5">
    <h1>Все записи пользователя
      {% if author.get_full_name %}
      {{ author.get_full_name }}
      {% else %}
      {{ author.username }}
      {% endif %}</h1>
    <h3>Всего записей: {{ post_list|length }} </h3>
    {% if following %}
      <a
        class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_unfollow' author.username %}" role="button"
      >
        Отписаться
      </a>
    {% else %}
        <a
          class="btn btn-lg btn-primary"
          href="{% url 'posts:profile_follow' author.username %}" role="button"
        >
          Подписаться
        </a>
     {% endif %}
    </div>
  {% for post in page_obj %}
  <article>
    <ul>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text }}</p>
    <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
  </article>
  {% if post.group %}Группа:  <a href="{% url 'posts:group' post.group.slug %}">{{ post.group }}</a>
  {% else %}
  <span>группа не указана</span>
  {% endif %}
  {% if not forloop.last %}
  <hr>{% endif %}
  {% endfor %}
  {% include '../includes/paginator.html' %}
</div>
{% endblock %}